name: Bug Report
labels: bug
title: "[Bug] "
body:
- type: markdown
  attributes:
    value: "Describe the Bug you're experiencing"
- type: markdown
  attributes:
    label: "How to reproduce the Bug"
