---
name: Bug Report
about: Use this template for reporting bugs.
labels: bug
title: "[Bug] "
---

## Bug Description
Please describe the Bug you're experiencing. Include any relevant screenshots or gifs.  

## Steps to reproduce
